"""Data models for Mati's prediction-scoring-evolution pipeline.

Every priority assignment is a *prediction*. Ground truth arrives later
(KEV additions, exploit publications, EPSS changes). The scorer compares
predictions to ground truth. The analyser finds failure patterns. The
synthesiser generates corrective skills.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class Priority(str, Enum):
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"
    P4 = "P4"


class Verdict(str, Enum):
    CORRECT = "CORRECT"
    MISS = "MISS"
    BAD_MISS = "BAD_MISS"
    FALSE_ALARM = "FALSE_ALARM"
    PENDING = "PENDING"


class RootCause(str, Enum):
    EPSS_UNDERWEIGHT = "EPSS_UNDERWEIGHT"
    VENDOR_BLIND_SPOT = "VENDOR_BLIND_SPOT"
    EXPLOIT_LAG = "EXPLOIT_LAG"
    CORRELATION_MISS = "CORRELATION_MISS"
    HISTORICAL_PATTERN = "HISTORICAL_PATTERN"
    CONTEXT_MISS = "CONTEXT_MISS"
    FALSE_ALARM_OVERREACTION = "FALSE_ALARM_OVERREACTION"
    UNKNOWN = "UNKNOWN"


class Outcome(str, Enum):
    EXPLOITED_IN_WILD = "exploited_in_wild"
    EXPLOIT_AVAILABLE = "exploit_available"
    EPSS_ESCALATED = "epss_escalated"
    NOT_EXPLOITED = "not_exploited"
    PENDING = "pending"


@dataclass
class PredictionContext:
    """Snapshot of data available at the time a priority was assigned."""
    is_kev: bool = False
    has_public_exploit: bool = False
    epss_score: float = 0.0
    cvss_score: float = 0.0
    affects_watchlist: bool = False
    clients_affected: list[str] = field(default_factory=list)
    vendor: str = ""
    product: str = ""


@dataclass
class Prediction:
    """A logged priority assignment — Mati's bet on how critical a CVE is."""
    id: str
    timestamp: str
    cve_id: str
    assigned_priority: Priority
    reasoning: str
    context: PredictionContext
    resolved: bool = False
    actual_outcome: Optional[Outcome] = None
    outcome_date: Optional[str] = None
    verdict: Optional[Verdict] = None
    verdict_detail: Optional[str] = None


@dataclass
class GroundTruthEvent:
    """A verifiable security outcome from an authoritative source."""
    cve_id: str
    event_type: Outcome
    event_date: str
    source: str  # "cisa_kev" | "github_exploit" | "epss"
    details: str = ""


@dataclass
class FailureRecord:
    """A single prediction failure with root cause analysis."""
    prediction_id: str
    cve_id: str
    assigned_priority: Priority
    correct_priority: Priority
    root_cause: RootCause
    analysis: str
    corrective_signal: str
    context_at_prediction: PredictionContext


@dataclass
class Scorecard:
    """Mati's accuracy metrics over a time period."""
    date: str
    period_days: int
    total_predictions: int
    resolved: int
    precision: float       # true_P1 / (true_P1 + false_P1)
    recall: float          # caught_before_KEV / total_KEV_additions
    avg_lead_time_days: float
    priority_accuracy: float
    miss_rate: float       # P3/P4 misses / total_KEV_additions
    trend: dict = field(default_factory=dict)


@dataclass
class EvolvedSkill:
    """A skill generated by the evolution engine from failure patterns."""
    name: str
    created: str
    root_cause: RootCause
    failures_analysed: int
    corrective_rule: str
    precision_before: float
    precision_after: Optional[float] = None
    validated: bool = False
    retired: bool = False
    retired_reason: Optional[str] = None
