"""Skill retrieval and injection for Mati.

Skills are short behavioural instructions stored as JSON. They are
injected into the system prompt at each turn so the LLM benefits from
accumulated threat-intelligence expertise.

Two tiers:
  base/   — shipped with Mati (curated threat intel heuristics)
  evolved/ — auto-generated by the evolution engine from failure patterns
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger("mati.skills")


def load_skills(skills_dir: str) -> list[dict[str, Any]]:
    """Load all skills from base/ and evolved/ directories."""
    skills: list[dict[str, Any]] = []
    root = Path(skills_dir)

    for sub in ("base", "evolved"):
        folder = root / sub
        if not folder.exists():
            continue
        for path in sorted(folder.glob("*.json")):
            try:
                skill = json.loads(path.read_text(encoding="utf-8"))
                skill["_source"] = sub
                skill["_path"] = str(path)
                skills.append(skill)
            except (json.JSONDecodeError, OSError) as exc:
                logger.warning("Skipping invalid skill %s: %s", path, exc)

    logger.info("Loaded %d skills (%s)", len(skills), skills_dir)
    return skills


def retrieve_skills(
    skills: list[dict[str, Any]],
    query: str,
    top_k: int = 6,
) -> list[dict[str, Any]]:
    """Retrieve the most relevant skills for a query.

    Uses simple keyword matching. A future version could use embedding
    similarity, but keyword matching is transparent, fast, and auditable
    — important properties for a security tool.
    """
    query_lower = query.lower()
    scored: list[tuple[float, dict[str, Any]]] = []

    for skill in skills:
        if skill.get("retired", False):
            continue

        # Score by keyword overlap
        keywords = skill.get("keywords", [])
        name = skill.get("name", "").lower()
        rule = skill.get("rule", "").lower()
        text = f"{name} {rule} {' '.join(keywords)}".lower()

        score = 0.0
        for word in query_lower.split():
            if len(word) < 3:
                continue
            if word in text:
                score += 1.0
            if word in name:
                score += 2.0  # name matches are stronger

        # Evolved skills get a small boost (they address known gaps)
        if skill.get("_source") == "evolved":
            score += 0.5

        if score > 0:
            scored.append((score, skill))

    scored.sort(key=lambda x: x[0], reverse=True)
    selected = [s for _, s in scored[:top_k]]
    logger.info("Retrieved %d/%d skills for query", len(selected), len(skills))
    return selected


def format_skill_injection(skills: list[dict[str, Any]]) -> str:
    """Format selected skills as a system prompt injection block."""
    if not skills:
        return ""

    lines = [
        "\n<mati_threat_intelligence_skills>",
        "The following rules are learned from real threat data. Apply them "
        "when assessing CVE priority and threat relevance.\n",
    ]

    for i, skill in enumerate(skills, 1):
        name = skill.get("name", "unnamed")
        rule = skill.get("rule", "")
        evidence = skill.get("evidence", "")
        source = skill.get("_source", "base")

        lines.append(f"[Skill {i}: {name}] (source: {source})")
        lines.append(f"Rule: {rule}")
        if evidence:
            lines.append(f"Evidence: {evidence}")
        lines.append("")

    lines.append("</mati_threat_intelligence_skills>")
    return "\n".join(lines)


def save_evolved_skill(
    skills_dir: str,
    name: str,
    rule: str,
    root_cause: str,
    evidence: str,
    keywords: list[str],
    failures_analysed: int,
    precision_before: float,
) -> Path:
    """Save a new evolved skill to disk."""
    evolved_dir = Path(skills_dir) / "evolved"
    evolved_dir.mkdir(parents=True, exist_ok=True)

    skill = {
        "name": name,
        "rule": rule,
        "root_cause": root_cause,
        "evidence": evidence,
        "keywords": keywords,
        "failures_analysed": failures_analysed,
        "precision_before": precision_before,
        "retired": False,
    }

    path = evolved_dir / f"{name}.json"
    path.write_text(json.dumps(skill, indent=2), encoding="utf-8")
    logger.info("Saved evolved skill: %s", path)
    return path
